name: Node.js CI
on:
  pull_request:
    branches: [ "master" ]
  push:

jobs:

  test:

    runs-on: ubuntu-latest

    env:
      YARN_IGNORE_NODE: 1

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 24.x]

    steps:

      - name: 'Checkout the repository'
        uses: actions/checkout@v4

      - name: Test with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test